#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "No u2f file provided"
  exit 1
fi

if ! [ -f "$1" ]; then
  echo "file not found: '$1'"
  exit 2
fi

udiskie -aNq || exit 1 &
upid="$!"

copy_uf2() {
  while ! [ -f "$2/CURRENT.UF2" ];do sleep 1;done
  echo "uploading file to $3 keyboard..."
  cp "$1" "$2"
  echo "waiting for $3 keyboard to dismount..."
  while [ -f "$2/CURRENT.UF2" ];do sleep 1;done
  echo "done: $3 keyboard"
}

mountdir=/run/media/$USER
declare -A sides=(
  ["left hand"]=GLV80LHBOOT
  ["right hand"]=GLV80RHBOOT
)

pids=()
echo "waiting for keyboard..."
for side in "${!sides[@]}";do
  dir="$mountdir/${sides[$side]}/"
  copy_uf2 "$1" "$dir" "$side" &
  pids+=("$!")
done

for pid in ${pids[*]};do
  wait $pid
done

kill $upid

echo "finished flashing"
